version: '3.3'
services:
  db:
    image: mongo:3.2
    volumes:
      - db:/data/db

  ui:
    build: ../src/ui
    image: ${username}/ui
    ports:
      - '9292:9292'
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
    build: ../src/post-py
    image: ${username}/post
    links:
      - "db:post_db"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  comment:
    build: ../src/comment
    image: ${username}/comment
    links:
      - "db:comment_db"
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

volumes:
  db:
