version: '3.3'
services:
  post_db:
    image: mongo:3.2
    container_name: mongodb
    volumes:
      - post_db:/data/db
    ports:
      - '27017:27017'
    networks:
      back_net:
        aliases:
          - post_db

  ui:
#    build: ./ui
#    image: ${username}/ui:${ui_version}
    image: ${username}/ui
    container_name: ui_v_${ui_version}
    ports:
      - ${ui_port}:9292/tcp
    networks:
      - front_net
      - back_net
  post:
#    build: ./post-py
#    image: ${username}/post:${post_version}
    image: ${username}/post
    container_name: post_v_${post_version}
    networks:
      back_net:
         aliases:
           - post
  comment:
#    build: ./comment
#    image: ${username}/comment:${comment_version}
    image: ${username}/comment
    container_name: comment_v_${comment_version}
    networks:
      back_net:
         aliases:
           - comment

  prometheus:
    image: ${username}/prometheus
    ports:
      - '9090:9090'
    networks:
      - back_net
      - front_net
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    networks:
      - back_net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  mongo_exporter:
    restart: 'always'
    ports:
    - '9001:9001'
    image: gpuliyar/mongo-exporter
    container_name: mongo-exporter-container
    environment:
    - 'MONGO_SERVICE=post_db'
    - 'MONGO_PORT=27017'
    depends_on:
    - post_db
    networks:
      back_net:
        aliases:
           - mongo_exporter

  blackbox:
    image: ${username}/blackbox
    container_name: blackbox
    hostname: blackbox
    ports:
      - 9115:9115
    restart: unless-stopped
    command:
      - "--config.file=/etc/blackbox/blackbox.yml"
    environment:
      TZ: "Europe/Moscow"
    networks:
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
