version: '3.3'
services:
  post_db:
    image: mongo:3.2
    container_name: mongodb
    volumes:
      - post_db:/data/db
    networks:
      back_net:
         aliases:
           - post_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${ui_version}
    container_name: ui_v_${ui_version}
    ports:
      - ${ui_port}:9292/tcp
    networks:
      - front_net
      - back_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${post_version}
    container_name: post_v_${post_version}
    networks:
      - back_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${comment_version}
    container_name: comment_v_${comment_version}
    networks:
      - back_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
